# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: xenial
os: linux
language: minimal
services:
  - docker
install: make build
script:
  - docker network create www
  - docker-compose up -d
  - sleep 10
  - make check
  - docker-compose down
