# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: xenial
os: linux
language: minimal
services:
  - docker
install: make build
script:
  - docker network create www
  - docker-compose up -d
  - docker ps
  - docker exec xq ls ./bin | grep 'xqerl'
  - docker exec xq ./bin/xqerl eval 'application:ensure_all_started(xqerl).'
  - docker-compose down
