# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-xqerl
sudo: required
dist: bionic
os: linux
language: minimal
services: docker
before_install: make network
install: make build
before_script: docker-compose up -d
script: sleep 10; make check-error-lines
after_script: docker-compose down
