version: '3.7'
services:
  xqerl:
    image: ${DOCKER_IMAGE}:${REPO_SHA}
    container_name: ${XQERL_CONTAINER_NAME}
    ports:
      - ${CONFIG_PORT}:${CONFIG_PORT}
    volumes:
      - type: volume
        source: db
        target: ${XQERL_HOME}/${CONFIG_DATA_DIR}
      - type: volume
        source: code
        target: ${XQERL_HOME}/${CONFIG_CODE_DIR}
volumes:
  db:
    driver: local
    name: ${CONFIG_DATA_DIR}
  code:
    driver: local
    name: ${CONFIG_CODE_DIR}

networks:
  default:
    external:
      name: $NETWORK

