version: '3.7'
services:
  xqerl:
    image: ${DOCKER_IMAGE}:${REPO_SHA}
    container_name: ${XQERL_CONTAINER_NAME}
    ports:
      - ${XQERL_PORT}:${CONFIG_PORT}
    volumes:     
      - type: volume
        source: db
        target: ${XQERL_HOME}/data
      - type: volume
        source: code
        target: ${XQERL_HOME}/code

volumes:
  db:
    driver: local
    name: ${DATA_DIR}
  code:
    driver: local
    name: ${CODE_DIR}

networks:
  default:
    external:
      name: $NETWORK

