name: Build Publish Docker Images
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  dockerize_xqerl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Docker Image From xqerl repo
        run: |
          make shell
          make build
      - name: list images
        run: docker image ls
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Push to Docker Hub
        run: |
          source .env
          docker push ${{ env.IMAGE_NAME }}:shell
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${REPO_SHA}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        run: |
          source .env
          docker push {{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GHPKG_VER}
      # make up
      #     printf %60s | tr ' ' '-' && echo
      # - name: Stop running xqerl
      #   run: |
      #     make down
