name: CI

on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          source .env
          docker buildx build \
          --target "shell" \
          --output "type=docker" \
          --tag "${DOCKER_IMAGE}:$(date --iso)-shell" \
          --tag "${DOCKER_IMAGE}:shell" \
          .                                     
          docker buildx build \
          --target "min" \
          --output "type=docker" \
          --tag "${DOCKER_IMAGE}:$(date --iso)-min" \
          --tag "${DOCKER_IMAGE}:latest" \
          --tag "${DOCKER_IMAGE}:${REPO_SHA}" \
          .
      - name: Build Docker Image From xqerl repo
        run: make build
      - name: Bring up xq container
        run: |
          make network
          make up
          sleep 5
          make info
          make inspect
      - name: Some Can Do Checks
        run: |
          # make check-can-run-expression
          # make check-copy-into-container
          make check-can-compile
          make check-can-use-external
      - name: DB Checks
        run: |
          make db-can-insert
          make db-can-get
          #make db-can-delete
      - name: restXQ Checks
        run: |
          make routes
          make route-head
          make route-head-redirect
          make route-get-xml
          make route-get-csv
          make route-get-json
          make route-get-html
          printf %60s | tr ' ' '=' && echo
          echo 'Accepting HTML form posted data'
          make route-post-form
          make route-form-multi
          echo 'Accepting posted data'
          make route-post-xml-file
          printf %60s | tr ' ' '=' && echo
      - name: Create, Update Delete, DB resources via restXQ
        run: |
          make route-create
          make route-get-created-resource
          make route-delete-resource
      - name: Take Down Docker Container
        run: make down
      - name: Docker Login In and Push to dockerhub
        run: |
          pwd
          ls -al .
          source .env
          echo "${DOCKER_TAG}"
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          make push
          make push TARGET=latest
          make push TARGET=shell
