name: Build Publish Docker Images
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  dockerize_xqerl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Docker Image From xqerl repo
        run: |
          make shell
          make build
      - name: list images
        run: docker image ls
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        run: |
          source .env
          docker push ${REPO_OWNER}/${REPO_NAME}:shell
          docker push ${REPO_OWNER}/${REPO_NAME}:latest
          docker push ${REPO_OWNER}/${REPO_NAME}:${REPO_SHA}
      # make up
      #     printf %60s | tr ' ' '-' && echo
      # - name: Stop running xqerl
      #   run: |
      #     make down
      #     printf %60s | tr ' ' '-' && echo
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.io --username ${REPO_OWNER} --password-stdin 
      # - name: Github Login In and Push to Github Packages
      #   run: |
      #     source .env
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${REPO_OWNER} --password-stdin
      #     docker push docker.pkg.github.com/${REPO_OWNER}/${REPO_NAME}/${RUN_NAME}:${GHPKG_VER}
