name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print GitHub Context # Debug step
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Build Docker Image From xqerl repo
      run: make build
    - name: Bring up xq container
      run: |
          make network
          make up
          sleep 5
    - name: Smoke Tests
      run: |
          echo ' - run basic xQuery expression' \
          && docker exec xq ./bin/xqerl eval \
          'xqerl:run("xs:token(\"cats\"), xs:string(\"dogs\"), true() ").'
          printf %60s | tr ' ' '-' && echo ''
          echo '  - copy xQuery files into container ' \
          && docker exec xq mkdir -p /tmp/fixtures \
          && docker cp ./fixtures xq:/tmp/fixtures
          printf %60s | tr ' ' '-' && echo ''
          echo '  - list copied container files' \
          docker exec xq ls /tmp
    - name: Take down docker container
      run: make down
    # - name: Docker Login In and Push to dockerhub 
    #   run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
    # - name: make push
