name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print GitHub Context # Debug step
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Build Docker Image From xqerl repo
      run: make build
    - name: Bring up xq container
      run: |
          make network
          make up
          sleep 5
          make info
    - name: Smoke Tests
      run: |
          make check-can-run-expression
          make check-copy-into-container
          make check-can-compile
          make check-can-use-external
          make check-can-use-node-to-xml
          make check-can-set-restXQ-routes
          make check-can-GET-restXQ-route

    - name: Take down docker container
      run: make down
    # - name: Docker Login In and Push to dockerhub 
    #   run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
    # - name: make push
