name: CI
on: push
jobs:
  dockerize_xqerl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build Docker Image From xqerl repo
        run: |
          make shell
          make build
      - name: set up local bin
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pushd $HOME/.local/bin && ln -s ${GITHUB_WORKSPACE}/bin/xq && popd
          which xq
      - name: Github login in and pull helper github packages
        run: |
          source .env
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${REPO_OWNER} --password-stdin &>/dev/null
          docker pull docker.pkg.github.com/grantmacken/alpine-scour/scour:0.0.2
          docker pull docker.pkg.github.com/grantmacken/alpine-zopfli/zopfli:0.0.1
      - name: Start running xqerl
        run: |
          make up
          printf %60s | tr ' ' '-' && echo
      - name: xq commands check
          printf %60s | tr ' ' '-' && echo
          echo ' list "xq" available commands'
          echo '> xq'
          xq
          printf %60s | tr ' ' '-' && echo
      - name: Stop running xqerl
        run: |
          make down
          printf %60s | tr ' ' '-' && echo
