name: CI
on: push
jobs:
  dockerize_xqerl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Docker Image From xqerl repo
        run: |
          make shell
          make build
      - name: Start running xqerl
        run: |
          make up
          printf %60s | tr ' ' '-'
      - name: xq commands check
        run: |
          bin/xq
          printf %60s | tr ' ' '-'
          echo ' - xq CRUD database actions [ put list get delete |  ] '
          bin/xq put example.com/usecase/employees.xml
          printf %60s | tr ' ' '-'
          bin/xq list example.com/usecase
          printf %60s | tr ' ' '-'
          bin/xq get example.com/usecase/employees.xml
          printf %60s | tr ' ' '-'
          bin/xq delete example.com/usecase/employees.xml
          printf %60s | tr ' ' '-'
          echo ' - xQuery actions [ query | compile | run ] ' 
          printf %60s | tr ' ' '-'
          bin/xq run 'current-date() => string()'
          bin/xq compile turtles.xq
          printf %60s | tr ' ' '-'
          bin/xq run turtles.xq turtles
          printf %60s | tr ' ' '-'
          echo ' - xqerl application actions [ call | eval ] run available xqerl erlang expressions' 
          bin/xq call xqldb_db_server exists http://example.com
          printf %60s | tr ' ' '-'
          bin/xq eval 'calendar:local_time().'
          printf %60s | tr ' ' '-'
          bin/echo ' - shell actions [ sh ] run alpine buzybox shell commands ' 
          printf %60s | tr ' ' '-'
          bin/xq  sh 'date -I'
          printf %60s | tr ' ' '-'
      - name: Stop running xqerl
        run: |
          make down
          printf %60s | tr ' ' '-'
      - name: Dockerhub Login In and Push to dockerhub
        run: |
          source .env
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.io --username ${REPO_OWNER} --password-stdin 
          docker push ${REPO_OWNER}/${REPO_NAME}:shell
          docker push ${REPO_OWNER}/${REPO_NAME}:latest
          docker push ${REPO_OWNER}/${REPO_NAME}:${REPO_SHA}
      - name: Github Login In and Push to Github Packages
        run: |
          source .env
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${REPO_OWNER} --password-stdin
          docker push docker.pkg.github.com/${REPO_OWNER}/${REPO_NAME}/${RUN_NAME}:${GHPKG_VER}
