name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print GitHub Context # Debug step
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Build Docker Image From xqerl repo
      run: make build
    - name: Bring up xq container
      run: |
          make network
          make up
          sleep 5
    - name: Smoke Tests
      run: |
          echo ' - run basic xQuery expression' \
          && docker exec xq ./bin/xqerl eval \
          'xqerl:run("xs:token(\"cats\"), xs:string(\"dogs\"), true() ").'
          printf %60s | tr ' ' '-' && echo ''
          echo '  - copy xQuery files into container ' \
          && docker cp ./fixtures xq:/tmp/.
          printf %60s | tr ' ' '-' && echo ''
          echo '  - list copied container files' \
          docker exec xq ls /tmp
          printf %60s | tr ' ' '-' && echo ''
          echo    ' - compile and run example xQuery' \
          && echo '   should return some text ' \
          && docker exec xq ./bin/xqerl eval \
          'xqerl:compile("/tmp/example.xq")'
          printf %60s | tr ' ' '-' && echo ''

    - name: Take down docker container
      run: make down
